### ISSUE TITLE
CollaborER-U

### ISSUE THREAD

**Issue by gpapadis** [ZJU-DAILY/CollaborER#2]
Hi! 
Thanks for sharing the code of your approach. It's very interesting and quite effective.
In the paper, you mention CollaborER-U, which applies to unsupervised settings. How exactly can this method be applied in practice?
I mean, how can we apply CollaborEM to the outcome of blocking, which comprises a set of candidate pairs that is not distinuighed into training and testing set?
Kind regards,
George

**Comment by Peng-fei-Wang** [comment]
Hi!
CollaborEM-U means that it can generate pseudo labels based on two tables. I think there are two ways to try: 1) If you do not have data from the two tables, you can get a subset of the two tables based on the candidate pairs, and generate pseudo labels based on this subset; 2) If you have data from the two tables, you can use this table to determine whether the candidate pairs satisfy the pseudo label strategy (ALG), in other words, whether they belong to a positive label or a negative label.

**Comment by gpapadis** [comment]
Thank you for the reply! Can you point me to the code that implements these two cases?

**Comment by Peng-fei-Wang** [comment]
You can refer to "seeds.py" for the main idea.

**Comment by gpapadis** [comment]
Thank you for your help!
